apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redpanda
  namespace: argocd
spec:
  project: default
  source:
    chart:  operator
    repoURL: https://charts.redpanda.com
    targetRevision: 0.4.20
    helm:
      releaseName: redpanda-operator
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: redpanda

